syntax = "proto3";

// ----- 客户端发来的请求 -----
message ClientRequest {
    optional bool percept_enable = 1;  // 开启/关闭 感知
    optional bool percept_enable_visual = 2;      // 开启/关闭 可视化
    optional bool percept_enable_img_save = 3;   // 开启/关闭 原图存储
    optional bool percept_enable_visual_save = 4;  // 开启/关闭 可视化图存储
    optional bool percept_enable_result_save = 5;  // 开启/关闭 结果存储

    optional string percept_enable_img_save_path = 6;
    optional string percept_enable_visual_save_path = 7;
    optional string percept_enable_result_save_path = 8;
}

// ----- 服务端返回的数据 -----
message TrackRow {
    float x1 = 1;
    float y1 = 2;
    float x2 = 3;
    float y2 = 4;
    string trackId = 5;
    float conf = 6;
    string cls = 7;
    repeated Masks mask = 8;
    bool isMove = 9;
    repeated float feats = 10;
}

message Masks {
    int32 x = 1;
    int32 y = 2;
}

// 单条指令的执行状态
message CommandStatus {
    string command = 1;      // 指令名称，例如 "percept_enable"
    string message = 2;      // 状态详情，"success"，"failure"
}

message MasksTracks {
    bytes timeStamp = 1;
    repeated TrackRow tracks = 2;
    repeated CommandStatus command_statuses = 3;
}

service ImageProcessing {
    rpc continuousInfo(stream ClientRequest) returns (stream MasksTracks);
}