# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imgs.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'imgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nimgs.proto\"<\n\x03Img\x12\x11\n\ttimeStamp\x18\x01 \x01(\x0c\x12\x0b\n\x03img\x18\x02 \x01(\x0c\x12\x15\n\rrequiresMasks\x18\x03 \x01(\x08\"+\n\x06Tracks\x12\x11\n\ttimeStamp\x18\x01 \x01(\x0c\x12\x0e\n\x06tracks\x18\x02 \x01(\x0c\";\n\x0bMasksTracks\x12\x11\n\ttimeStamp\x18\x01 \x01(\x0c\x12\x19\n\x06tracks\x18\x02 \x03(\x0b\x32\t.TrackRow\"\x9b\x01\n\x08TrackRow\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x0f\n\x07trackId\x18\x05 \x01(\t\x12\x0c\n\x04\x63onf\x18\x06 \x01(\x02\x12\x0b\n\x03\x63ls\x18\x07 \x01(\t\x12\x14\n\x04mask\x18\x08 \x03(\x0b\x32\x06.Masks\x12\x0e\n\x06isMove\x18\t \x01(\x08\x12\r\n\x05\x66\x65\x61ts\x18\n \x03(\x02\"\x1d\n\x05Masks\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32\xd5\x01\n\x0fImageProcessing\x12\x1e\n\x0bsingleTrack\x12\x04.Img\x1a\x07.Tracks\"\x00\x12\"\n\nsingleMask\x12\x04.Img\x1a\x0c.MasksTracks\"\x00\x12&\n\x0f\x63ontinuousTrack\x12\x04.Img\x1a\x07.Tracks\"\x00(\x01\x30\x01\x12*\n\x0e\x63ontinuousMask\x12\x04.Img\x1a\x0c.MasksTracks\"\x00(\x01\x30\x01\x12*\n\x0e\x63ontinuousInfo\x12\x04.Img\x1a\x0c.MasksTracks\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMG']._serialized_start=14
  _globals['_IMG']._serialized_end=74
  _globals['_TRACKS']._serialized_start=76
  _globals['_TRACKS']._serialized_end=119
  _globals['_MASKSTRACKS']._serialized_start=121
  _globals['_MASKSTRACKS']._serialized_end=180
  _globals['_TRACKROW']._serialized_start=183
  _globals['_TRACKROW']._serialized_end=338
  _globals['_MASKS']._serialized_start=340
  _globals['_MASKS']._serialized_end=369
  _globals['_IMAGEPROCESSING']._serialized_start=372
  _globals['_IMAGEPROCESSING']._serialized_end=585
# @@protoc_insertion_point(module_scope)
