### konkaV2.0 server configuration file for konka_grpc_server.py ###

DEVICE: "cuda:0"

model_cfg:
  iou_threshold: 0.7
  conf_threshold: 0.1
  model_seg: "trt_engines/yoloe-11l-merged-seg.engine"
#  model_det: "trt_engines/yoloe-v8l-det.engine"
  model_dual: True

visual_cfg:
  visual: True
  video_save: False
  img_show: False
  img_save: False
  output_path: "results/output.avi"
  images_path: "results/images"


server_cfg:
  server_ip: "0.0.0.0"
  server_port: "50051"
  max_send_message_length: 1 * 1024 * 1024  # 1mb
  max_receive_message_length: 1 * 1024 * 1024
  max_workers: 1  # max number of workers can be connected
