### konkaV2.0 server configuration file for konka_grpc_server.py ###

DEVICE: "cuda:0"

model_cfg:
  iou_threshold: 0.7
  conf_threshold: 0.2
  model_seg: "trt_engines/yoloe-11l-merged-seg.engine"
  model_dual: True

visual_cfg:
  video_save: False
  img_show: True
  img_save: False
  img_result_save: False
  json_result_save: False
  video_path: "results/video.avi"
  images_path: "results/images"
  images_result_path: "results/images_result"
  json_result_path: "results/json_result"

ros_cfg:
  topic: "/head_camera/color/image_raw"
  target_fps: 10

server_cfg:
  server_ip: "0.0.0.0"
  server_port: "50051"
  max_send_message_length: 1 * 1024 * 1024  # 1mb
  max_receive_message_length: 1 * 1024 * 1024
  max_workers: 1  # max number of workers can be connected
